global:
  scrape_interval: 10s

rule_files:
  - /etc/prometheus/config/alert-rules.yaml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093

scrape_configs:
  - job_name: 'casper'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'localhost:8888'
  - job_name: 'chain'
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'localhost:8123'
