global:
  scrape_interval: 10s

rule_files:
  - /etc/prometheus/config/alert-rules.yaml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093

scrape_configs:
  - job_name: 'casper'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'localhost:8888'
  - job_name: 'chain'
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'localhost:8123'
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_rpc]
    static_configs:
      - targets:
        - 'localhost:7777'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
